[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
categories = ["command-line-utilities", "development-tools", "wasm"]
description = "The WebAssembly Pre-Initializer"
documentation = "https://docs.rs/wizer"
edition = "2018"
exclude = ["**.wasm"]
homepage = "https://github.com/bytecodealliance/wizer"
license = "Apache-2.0 WITH LLVM-exception"
name = "wizer"
readme = "./README.md"
repository = "https://github.com/bytecodealliance/wizer"
version = "4.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "wizer"
required-features = ["env_logger", "structopt"]

[[bench]]
name = "regex"
harness = false

[[bench]]
name = "uap"
harness = false

[dependencies]
anyhow = "1.0.38"
cap-std = "2.0.0"
env_logger = { version = "0.10", optional = true }
log = "0.4.14"
rayon = "1.5.0"
structopt = { version = "0.3.21", optional = true }
wasi-cap-std-sync = { workspace = true }
wasm-encoder = "0.30.0"
wasmparser = "0.106.0"
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }

# Enable this dependency to get messages with WAT disassemblies when certain
# internal panics occur.
[dependencies.wasmprinter]
workspace = true
optional = true

[workspace.dependencies]
wasmprinter = "0.2.60"
wasmtime = "17"
wasmtime-wasi = "17"
wasi-cap-std-sync = "17"


[dev-dependencies]
criterion = "0.5.1"
env_logger = "0.10.0"
wasmprinter = { workspace = true }
wat = "1.0.67"

[workspace]
members = [
    "benches/regex-bench",
    "benches/uap-bench",
    "fuzz",
    "tests/regex-test",
]

[profile.bench]
debug = true
